version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.native
    ports:
      - 127.0.0.1:8080:8080
  mongo:
    image: mongo:4.4.4
    ports:
      - 127.0.0.1:27017:27017
